/* jahmm package - v0.6.1 */

/*
  *  Copyright (c) 2004-2006, Jean-Marc Francois.
 *
 *  This file is part of Jahmm.
 *  Jahmm is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  Jahmm is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Jahmm; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package be.ac.ulg.montefiore.run.jahmm.io;

import java.io.IOException;
import java.io.StreamTokenizer;

import be.ac.ulg.montefiore.run.jahmm.ObservationInteger;


/**
 * Reads an {@link be.ac.ulg.montefiore.run.jahmm.ObservationInteger
 * ObservationInteger} up to (and including) a semi-colon.
 * <p>
 * The format of this observation is a simple integer ([+-]?[0123456789]+).
 * <p>
 * For example, reading
 * <pre>76;</pre>
 * creates an observation such as the one generated by
 * <code>new ObservationInteger(76);</code>
 */
public class ObservationIntegerReader
extends ObservationReader<ObservationInteger>
{	
	// Maximum value of the obserations read + 1
	private int nbElements;
	
	
	/**
	 * Constructs a reader of {@link ObservationInteger ObservationInteger}.
	 */
	public ObservationIntegerReader()
	{
		nbElements = Integer.MAX_VALUE;
	}
	
	
	/**
	 * Constructs a reader of {@link ObservationInteger ObservationInteger}.
	 * Verifies the maximum value of the observations read.
	 *
	 * @param nbElements The permitted number of different elements.  Each
	 *        value read must be <tt>0 &le; value &lt; nbElements</tt>.
	 */
	public ObservationIntegerReader(int nbElements)
	{
		if (nbElements <= 0)
			throw new IllegalArgumentException("Nb of elements must be " +
			"positive");
		
		this.nbElements = nbElements;
	}
	
	
	/**
	 * Reads an {@link be.ac.ulg.montefiore.run.jahmm.ObservationInteger
	 * ObservationInteger} reader, as explained in 
	 * {@link ObservationReader ObservationReader}.
	 *
	 * @param st A stream tokenizer.
	 * @return The {@link be.ac.ulg.montefiore.run.jahmm.ObservationInteger
	 *         ObservationInteger} read.
	 */
	public ObservationInteger read(StreamTokenizer st) 
	throws IOException, FileFormatException
	{	
		ObservationInteger oi;
		
		st.ordinaryChar((int)'.');
		
		if (st.nextToken() == StreamTokenizer.TT_NUMBER) {
			if (st.nval > nbElements)
				throw new FileFormatException(st.lineno(),
						"Integer higher than maximum value " + (nbElements-1));
			oi = new ObservationInteger((int) st.nval);
		} else
			throw new FileFormatException(st.lineno(), "Integer expected");
		
		if (st.nextToken() != (int) ';')
			throw new FileFormatException(st.lineno(), "';' expected");
		
		ObservationSequencesReader.initSyntaxTable(st);
		
		return oi;
	}
}
